---
ID: "bdd7a44b-647f-48ae-b6de-c8cd8a034710"
Parent: "15a4a56d-cef2-4eed-a430-f865fc12337f"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/Migration/migration/Presentation/Headless Variants/FooterST/Default
BranchID: "cf133985-e19f-4822-b008-563f1c4d4630"
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "3d04447f-1e39-4ff8-988f-b76db482840f"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{AD0AFBCF-32A6-44F1-BDE1-F657D21E580E}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260907T114047Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\mateen.shaikh@techxot.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\mateen.shaikh@techxot.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0eac02e5-5655-455b-bf7a-e72fb18bcf04"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\mateen.shaikh@techxot.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260907T114047Z
