---
ID: "4a06702e-0b37-4f3c-ac80-e6778b1f6c44"
Parent: "0ab92769-db7b-4fae-9a46-c87881849eab"
Template: "202be47e-a51d-4099-94a5-6ba8a493c326"
Path: /sitecore/content/Migration/migration/Home/Services
SharedFields:
  - ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
    Hint: __Renderings
    Value: |
      <r xmlns:p="p" xmlns:s="s"
        p:p="1">
        <d
          id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
          <r
            uid="{62630425-D2C2-4B6A-B928-CC41EF531EA7}"
            p:before="*"
            s:ds="{CAB6C43E-6832-4039-A889-D6C43A08E0C5}"
            s:id="{2FFDCA48-9C69-4DBC-9465-5671EDC08664}"
            s:par="Reset Caching Options&amp;GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D%7C%7BC3767F66-03BE-4587-B22C-C0D28B45C319%7D%7C%7B436C37A1-CC36-4176-97C0-F1C48104E601%7D&amp;FieldNames=%7B38EE9060-1F30-4D95-ADDC-5AB31C4CDCBC%7D&amp;Styles&amp;RenderingIdentifier&amp;DynamicPlaceholderId=3"
            s:ph="headless-main"
            s:ccb="Clear on publish" />
          <r
            uid="{CCCCF653-C3F0-4E3D-A3FD-F883A76A4B78}"
            p:after="*[1=2]"
            s:ds="{6F84DD76-18DB-4018-9E79-E5F087EC5345}"
            s:id="{FBC6B856-98A3-40FD-B11D-8C807A336B87}"
            s:par="Reset Caching Options&amp;GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D%7C%7BC3767F66-03BE-4587-B22C-C0D28B45C319%7D%7C%7B436C37A1-CC36-4176-97C0-F1C48104E601%7D&amp;FieldNames=%7B437CB44D-A04C-466A-8019-5FAC4DFDDB59%7D&amp;Styles&amp;RenderingIdentifier&amp;DynamicPlaceholderId=2"
            s:ph="headless-main"
            s:ccb="Clear on publish" />
        </d>
      </r>
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
            Hint: __Created
            Value: 20260903T064943Z
          - ID: "4bb021cf-fa43-4a51-85d6-00797a42cb4c"
            Hint: Title
            Value: Services
          - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
            Hint: NavigationTitle
            Value: Services
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "69595e7d-65fc-4c01-a331-ebe08fde92eb"
          - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
            Hint: __Updated by
            Value: |
              sitecore\mateen.shaikh@techxot.com
          - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
            Hint: __Updated
            Value: 20260915T095249Z
